### PR TITLE
API returns more data when queried

### PR DESCRIPTION
**Pull request by RogerTangos**
API now returns drs.data and drs edges (along with scores)

This should be straightforward, but I like to make sure someone else looks at these things before they get pulled in.

### CODE REVIEW

**Comment by RogerTangos** [comment]
If we only sent one at a time, in some cases, we'd be asking Algebra to do the same queries twice.

Given that we don't know where the bottleneck will be, or how convenient the data will be for front end applications, I think that we should send both for now. If a user is just interested in the data, they can just use that.

It's always (very easily) changeable later on.

**Comment by raulcf** [comment]
> If we only sent one at a time, in some cases, we'd be asking Algebra to do the same queries twice.

The idea I propose is to send one or two, instead of always two. That way, if we know we only need the data, we can just retrieve that first. My worry is that the provenance graph can be quite big in many cases. 

Having said that, and since it's easy to change anyway, I'm fine with doing this later.

Should I merge?

**Comment by RogerTangos** [comment]
Yep!

Sorry, I should have said "If we only send data in some cases, if the user then asked for edges afterwards, we'd need to run the algebra twice."

**Comment by raulcf** [comment]
All right, I'm merging. Can you open an issue (enhancement or similar) for later? Just to make sure we keep track of this.

**Pull request merged**
